# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ProtoRpc.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class StatusEnum(betterproto.Enum):
    RPC_SUCCESS = 0
    RPC_BAD_RESOLVER_LOOKUP = 1
    RPC_BAD_CALLSET_UNPACK = 2
    RPC_BAD_HANDLER_LOOKUP = 3
    RPC_HANDLER_ERROR = 4


@dataclass(eq=False, repr=False)
class ProtoRpcHeader(betterproto.Message):
    seqn: int = betterproto.uint32_field(1)
    no_reply: bool = betterproto.bool_field(2)
    status: "StatusEnum" = betterproto.enum_field(3)
    which_callset: int = betterproto.uint32_field(4)
