# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: TestRpc.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class AddCall(betterproto.Message):
    a: int = betterproto.int32_field(1)
    b: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class AddReply(betterproto.Message):
    sum: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class HandlerErrorCall(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class HandlerErrorReply(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SetStructCall(betterproto.Message):
    var_int32: int = betterproto.int32_field(1)
    var_uint32: int = betterproto.uint32_field(2)
    var_int64: int = betterproto.int64_field(3)
    var_uint64: int = betterproto.uint64_field(4)
    var_uint32_array: List[int] = betterproto.uint32_field(5)
    var_bool: bool = betterproto.bool_field(6)
    var_string: str = betterproto.string_field(7)
    var_bytes: bytes = betterproto.bytes_field(8)


@dataclass(eq=False, repr=False)
class SetStructReply(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class TestCallset(betterproto.Message):
    add_call: "AddCall" = betterproto.message_field(1, group="msg")
    add_reply: "AddReply" = betterproto.message_field(2, group="msg")
    setstruct_call: "SetStructCall" = betterproto.message_field(3, group="msg")
    setstruct_reply: "SetStructReply" = betterproto.message_field(4, group="msg")
    handlererror_call: "HandlerErrorCall" = betterproto.message_field(5, group="msg")
    handlererror_reply: "HandlerErrorReply" = betterproto.message_field(6, group="msg")
