/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "RtosUtilsRpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rtos_TaskInfo, rtos_TaskInfo, AUTO)


PB_BIND(rtos_GetSystemTasks_call, rtos_GetSystemTasks_call, AUTO)


PB_BIND(rtos_GetSystemTasks_reply, rtos_GetSystemTasks_reply, 2)


PB_BIND(rtos_RtosUtilsCallset, rtos_RtosUtilsCallset, 2)




